config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :forum_threads do
    resources :posts
  end

  get 'tdestroy_all' => 'forum_threads#destroy_all'

  root 'forum_threads#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forum_thread.rb
# == Schema Information
#
# Table name: forum_threads
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  tenant_id  :integer
#
# Indexes
#
#  index_forum_threads_on_tenant_id  (tenant_id)
#  index_forum_threads_on_user_id    (user_id)
#

class ForumThread < ApplicationRecord
  has_many :posts, dependent: :destroy
  belongs_to :user

  accepts_nested_attributes_for :posts

  default_scope { where(tenant_id: Thread.current[:tenant_id]) }

  validates :title, presence: true
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id              :integer          not null, primary key
#  content         :text
#  forum_thread_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :integer
#
# Indexes
#
#  index_posts_on_forum_thread_id  (forum_thread_id)
#  index_posts_on_user_id          (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (forum_thread_id => forum_threads.id)
#

class Post < ApplicationRecord
  belongs_to :forum_thread
  belongs_to :user

  validates :content, presence: true
end

app/models/tenant.rb
# == Schema Information
#
# Table name: tenants
#
#  id         :integer          not null, primary key
#  host_name  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tenant < ApplicationRecord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  tenant_id              :integer
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_tenant_id             (tenant_id)
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_lang
  before_action :set_tz
  before_action :set_tenant

  def set_lang
    I18n.locale = 'id'
  end

  def set_tz
    Time.zone = 'Asia/Jakarta'
  end

  def set_tenant
    tenant = Tenant.find_or_create_by(host_name: request.host)
    Thread.current[:tenant_id] = tenant.id
  end

end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  before_action :set_forum_thread, only: [:show, :edit, :update, :destroy]

  # GET /forum_threads
  # GET /forum_threads.json
  def index
    @forum_threads = ForumThread.all
  end

  # GET /forum_threads/1
  # GET /forum_threads/1.json
  def show
  end

  # GET /forum_threads/new
  def new
    @forum_thread = ForumThread.new
    @forum_thread.posts = [ Post.new(user: current_user) ]
  end

  # GET /forum_threads/1/edit
  def edit
  end

  # POST /forum_threads
  # POST /forum_threads.json
  def create
    @forum_thread = ForumThread.new(forum_thread_params)
    @forum_thread.user = current_user
    @forum_thread.posts.first.user = current_user

    respond_to do |format|
      if @forum_thread.save
        format.html { redirect_to @forum_thread, notice: 'Forum thread was successfully created.' }
        format.json { render :show, status: :created, location: @forum_thread }
      else
        format.html { render :new }
        format.json { render json: @forum_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forum_threads/1
  # PATCH/PUT /forum_threads/1.json
  def update
    respond_to do |format|
      if @forum_thread.update(forum_thread_params)
        format.html { redirect_to @forum_thread, notice: 'Forum thread was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum_thread }
      else
        format.html { render :edit }
        format.json { render json: @forum_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forum_threads/1
  # DELETE /forum_threads/1.json
  def destroy
    @forum_thread.destroy
    respond_to do |format|
      format.html { redirect_to forum_threads_url, notice: 'Forum thread was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_all
    ForumThread.destroy_all
    
    render plain: 'ok'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum_thread
      @forum_thread = ForumThread.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_thread_params
      params.require(:forum_thread)
        .permit(
          :title,
          posts_attributes: [ :content, :nickname, :email ]
        )
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.forum_thread = ForumThread.find(params['forum_thread_id'])
    @post.user = current_user
    @post
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.forum_thread = ForumThread.find(params['forum_thread_id'])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post.forum_thread, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :nick_name, :email, :forum_thread_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_of(object)
    object.user.email
  end
end

app/views/forum_threads/_form.html.erb
<%= form_with(model: forum_thread, local: true) do |form| %>
  <% if forum_thread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(forum_thread.errors.count, "error") %> prohibited this forum_thread from being saved:</h2>

      <ul>
      <% forum_thread.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :forum_thread_title %>
  </div>

  <%= form.fields_for :posts do |post_form| %>
    <div class="field">
      <div class="field">
        <%= post_form.label :content %>
        <%= post_form.text_area :content, id: :post_content %>
      </div>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/forum_threads/edit.html.erb
<h1>Editing Forum Thread</h1>

<%= render 'form', forum_thread: @forum_thread %>

<%= link_to 'Show', @forum_thread %> |
<%= link_to 'Back', forum_threads_path %>

app/views/forum_threads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Forum Threads</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Jumlah Balasan</th>
      <th>Thread Starter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forum_threads.each do |forum_thread| %>
      <tr>
        <td><%= link_to forum_thread.title, forum_thread %></td>
        <td><%= forum_thread.posts.count %></td>
        <td><%= user_of forum_thread %>
        <td><%= link_to 'Show', forum_thread %></td>
        <td><%= link_to 'Edit', edit_forum_thread_path(forum_thread) %></td>
        <td><%= link_to 'Destroy', forum_thread, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user %>
  <%= link_to 'New Forum Thread', new_forum_thread_path %>
<% end %>

app/views/forum_threads/new.html.erb
<h1>New Forum Thread</h1>

<%= render 'form', forum_thread: @forum_thread %>

<%= link_to 'Back', forum_threads_path %>

app/views/forum_threads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1>
    <%= @forum_thread.title %>
  </h1>
</p>

<% @forum_thread.posts.each do |post| %>
  <div class="post-container">
    <div class="post">
      <%= post.content %>
    </div>

    <div class="infobar">
      <strong>
        <%= user_of post %>
      </strong>
      pada
      <span title="<%= post.created_at.iso8601 %>">
        <%= time_ago_in_words(post.created_at) %>
      </span>
      yang lalu
    </div>
  </div>
<% end %>

<%= link_to 'Reply', new_forum_thread_post_path(@forum_thread) %>
<%= link_to 'Edit', edit_forum_thread_path(@forum_thread) %>
<%= link_to 'Back', forum_threads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div id="content">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, url: [@post.forum_thread, post], local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Nick name</th>
      <th>Email</th>
      <th>Forum thread</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= post.nick_name %></td>
        <td><%= post.email %></td>
        <td><%= post.forum_thread %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', @forum_thread %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Nick name:</strong>
  <%= @post.nick_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @post.email %>
</p>

<p>
  <strong>Forum thread:</strong>
  <%= @post.forum_thread %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_header.html.erb
<div id="header">
  <div id="hero">
    <h1><%= link_to 'SuperForum', '/' %></h1>
  </div>
  <% if current_user.nil? %>
    <%= render 'shared/header_guest' %>
  <% else %>
    <%= render 'shared/header_member' %>
  <% end %>
</div>

app/views/shared/_header_guest.html.erb
<div class="right">
  <%= link_to 'Beranda', '/' %>
  |
  <%= link_to "Daftar", new_user_registration_path %>
  |
  <%= link_to "Masuk", new_user_session_path %>
</div>
<div class="left">
  Halo, pengunjung!
</div>

app/views/shared/_header_member.html.erb
<div class="right">
  <%= link_to 'Beranda', '/' %>
  |
  <%= link_to "Edit Profil", edit_user_registration_path %>
  |
  <%= link_to "Keluar", destroy_user_session_path, :method => :delete %>
</div>
<div class="left">
  Halo, <%= current_user.email %>
</div>